#!/usr/bin/env bash

set -euEo pipefail

main()
{
    uvx \
        --from="git+https://github.com/radium226/variables.git" \
            variables \
                exec \
                    -v "./variables.yaml" \
                    -- \
                        uv run vpn-passthrough \
                            create-tunnel \
                                --username="{{ PIA_USER }}" \
                                --password="{{ PIA_PASS }}" \
                                --number-of-ports-to-forward=1 \
                                    "test"
}

main "${@}"