#!/usr/bin/env bash

set -euEo pipefail


# --dns-override "*.internal=10.0.0.1"


main()
{
    local app_dir
    app_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../app" && pwd)"

    uv --directory "${app_dir}" run vpn-passthrough \
        create-tunnel \
            --backend-name="pia" \
            --dns-override "*.internal=10.0.0.1" \
            --extra-route "10.0.0.1/32" \
                "dummy"
}

main "${@}"
