#!/usr/bin/env bash

set -euEo pipefail

main()
{
    local root
    root="$(git rev-parse --show-toplevel)"

    log "Installing Arch Linux package with pacman..."
    find "${root}/packages/arch" -mindepth 1 -maxdepth 1 -type "f" -name "*.pkg.tar.zst" -exec sudo pacman -U --noconfirm "{}" \;
}

log() {
    echo "[$(date --iso-8601=seconds)] ${*}" >&2
}

main "${@}"
