#!/usr/bin/env bash

set -euEo pipefail

main()
{
    local root
    root="$(git rev-parse --show-toplevel)"

    log "Building source distributions with uv..."
    uv --directory "${root}/app" build --all-packages --sdist --out-dir "${root}/packages/arch"

    log "Building Arch Linux package with makepkg..."
    cd "${root}/packages/arch"
    makepkg \
        --syncdeps \
        --force \
        --noconfirm \
        --clean \
        --cleanbuild \
        "${@}"
    

    log "Cleaning up source distributions..."
    find "." -mindepth 1 -maxdepth 1 -type "f" -name "*.tar.gz" -delete
}

log() {
    echo "[$(date --iso-8601=seconds)] ${*}" >&2
}

main "${@}"
