#!/usr/bin/env bash

set -euEo pipefail

main()
{
    uvx \
        --from="git+https://github.com/radium226/variables.git" \
            variables exec \
                -- \
                    sudo -E -u root -g "$(id -gn)" uv run vpn-passthrough start-server
}

main "${@}"